# Generated by Django 5.0.2 on 2024-03-25 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('equipo', models.CharField(max_length=60)),
                ('edad', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Talento',
                'verbose_name_plural': 'Talentos',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='directortecnico',
            options={'ordering': ['id'], 'verbose_name': 'DirectorTecnico', 'verbose_name_plural': 'DirectoresTecnicos'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['id'], 'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
